# Generated by Django 4.1.5 on 2023-05-09 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='RUT del Cliente')),
                ('nombreCliente', models.CharField(max_length=20, verbose_name='Nombre del Cliente')),
                ('apellidoCliente', models.CharField(max_length=20, verbose_name='Apellido del Cliente')),
                ('correoCliente', models.EmailField(max_length=40, verbose_name='Correo del Cliente')),
                ('fonoCliente', models.IntegerField(verbose_name='Fono del Cliente')),
                ('direccionCliente', models.CharField(max_length=50, verbose_name='Direccion del Cliente')),
            ],
            options={
                'ordering': ['apellidoCliente'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID del Evento')),
                ('fechaEvento', models.DateField(verbose_name='Fecha del Evento')),
                ('cantPersonas', models.IntegerField(verbose_name='Cantidad de Personas del Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID del Pedido')),
                ('fechaPedido', models.DateField(blank=True, verbose_name='Fecha del Pedido')),
                ('fechaEntrega', models.DateField(blank=True, verbose_name='Fecha Entrega del Pedido')),
                ('precioPedido', models.IntegerField(verbose_name='Precio del Pedido')),
            ],
            options={
                'ordering': ['-fechaEntrega'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID del Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del Producto')),
                ('descProducto', models.CharField(max_length=60, verbose_name='Descripcion del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantProducto', models.IntegerField(verbose_name='Cantidad del o los Productos')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_pedido', to='WebSE.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSE.pedido', verbose_name='ID del Producto')),
                ('rutCliente', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.PROTECT, to='WebSE.cliente', verbose_name='RUT del Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('nroCotizacion', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Numero de la Cotizacion')),
                ('nombreCotizacion', models.CharField(max_length=100, verbose_name='Nombre de la Cotizacion')),
                ('idEvento', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.PROTECT, to='WebSE.evento', verbose_name='ID del Evento')),
                ('rutCliente', models.ForeignKey(max_length=9, on_delete=django.db.models.deletion.PROTECT, to='WebSE.cliente', verbose_name='RUT del Cliente')),
            ],
        ),
    ]
