# Generated by Django 4.0.5 on 2023-05-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0003_alter_evento_imgevento_alter_producto_imgproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_consulta', models.IntegerField(choices=[[0, 'consulta'], [1, 'reclamo'], [2, 'sugerencia'], [3, 'fecilitaciones']])),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
