# Generated by Django 4.2 on 2023-05-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0004_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='idEvento',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='rutCliente',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='idPedido',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='idProducto',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='rutCliente',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Cotizacion',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
