# Generated by Django 4.2 on 2023-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0008_producto_cantpersonas_producto_imagenproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseñaCliente',
            field=models.CharField(default='', max_length=50),
        ),
    ]
