# Generated by Django 4.2 on 2023-06-06 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0009_cliente_contraseñacliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombreCliente', 'apellidoCliente']},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='idEvento',
        ),
        migrations.AddField(
            model_name='evento',
            name='nroCotizacion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='WebSE.cotizacion', verbose_name='Numero de la Cotizacion'),
        ),
    ]
