# Generated by Django 4.2 on 2023-06-09 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0010_alter_cliente_options_remove_cotizacion_idevento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(max_length=100, verbose_name='Nombre del Servicio')),
                ('precioServicio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio del Servicio')),
                ('tipo_evento', models.CharField(choices=[('matrimonio', 'Matrimonio'), ('cumpleaños', 'Cumpleaños'), ('aniversario', 'Aniversario'), ('fiesta_corporativa', 'Fiesta Corporativa')], default='matrimonio', max_length=20)),
                ('tipo_servicio', models.CharField(choices=[('bar', 'Bar'), ('aperitivos', 'Aperitivos'), ('entrada', 'Entrada'), ('plato_principal', 'Plato Principal'), ('postre', 'Postre'), ('personal', 'Personal'), ('vajilla_cristaleria', 'Vajilla y Cristalería'), ('dj', 'DJ'), ('iluminacion', 'Iluminación'), ('decoracion', 'Decoración'), ('fotografo', 'Fotógrafo'), ('torta', 'Torta')], default='bar', max_length=30)),
                ('subtipo_servicio', models.CharField(blank=True, choices=[('tragos', 'Tragos'), ('bar_adicional', 'Bar Adicional'), ('canapes', 'Canapés'), ('tapaditos', 'Tapaditos'), ('brochetas', 'Brochetas'), ('empanadas_cocktail', 'Empanadas Cocktail')], max_length=100)),
            ],
        ),
    ]
