# Generated by Django 4.2 on 2023-06-13 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0011_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTitular', models.CharField(max_length=50, verbose_name='Nombre del Titular')),
                ('numeroTarjeta', models.CharField(max_length=16, verbose_name='Número de la Tarjeta')),
                ('fechaExpiracion', models.DateField(verbose_name='Fecha de Expiración')),
                ('codigoSeguridad', models.CharField(max_length=4, verbose_name='Código de Seguridad')),
                ('rutTitular', models.IntegerField(verbose_name='RUT del Titular')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='WebSE.cliente')),
            ],
        ),
    ]
