# Generated by Django 4.2 on 2023-06-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0013_alter_tarjeta_fechaexpiracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fonoCliente',
            field=models.IntegerField(max_length=9, verbose_name='Fono del Cliente'),
        ),
    ]
