# Generated by Django 4.2 on 2023-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0014_alter_cliente_fonocliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fonoCliente',
            field=models.IntegerField(verbose_name='Fono del Cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precioServicio',
            field=models.IntegerField(max_length=8, verbose_name='Precio del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subtipo_servicio',
            field=models.CharField(blank=True, choices=[('tragos', 'Tragos'), ('bar_adicional', 'Bar Adicional'), ('canapes', 'Canapés'), ('tapaditos', 'Tapaditos'), ('brochetas', 'Brochetas'), ('empanadas_cocktail', 'Empanadas Cocktail')], default='', max_length=100),
        ),
    ]
