# Generated by Django 4.2 on 2023-06-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0015_alter_cliente_fonocliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precioServicio',
            field=models.IntegerField(verbose_name='Precio del Servicio'),
        ),
    ]
