# Generated by Django 4.2 on 2023-06-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0016_alter_servicio_precioservicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precioServicio',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio del Servicio'),
        ),
    ]
