# Generated by Django 4.2 on 2023-06-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0019_servicio_imagenproducto_servicio_nombrepersona'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='imagenProducto',
            new_name='imagenServicio',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subtipo_servicio',
            field=models.CharField(blank=True, choices=[('tragos', 'Tragos'), ('bar_adicional', 'Bar Adicional'), ('canapes', 'Canapés'), ('tapaditos', 'Tapaditos'), ('brochetas', 'Brochetas'), ('empanadas_cocktail', 'Empanadas Cocktail'), ('bartender', 'Bartender'), ('garzón/a', 'Garzón/a'), ('fotógrafo/a', 'Fotógrafo/a')], default='', max_length=100),
        ),
    ]
