# Generated by Django 4.2 on 2023-06-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0022_alter_servicio_imagenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='servicios',
            field=models.ManyToManyField(to='WebSE.servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombrePersona',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nombre de quien imparte el servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='subtipo_servicio',
            field=models.CharField(blank=True, choices=[('tragos', 'Tragos'), ('bar_adicional', 'Bar Adicional'), ('canapes', 'Canapés'), ('tapaditos', 'Tapaditos'), ('brochetas', 'Brochetas'), ('empanadas_cocktail', 'Empanadas Cocktail'), ('bartender', 'Bartender'), ('garzón/a', 'Garzón/a'), ('cocinero', 'Cocinero'), ('fotógrafo/a', 'Fotógrafo/a'), ('dj', 'DJ'), ('vajilla', 'Vajilla'), ('cristaleria', 'Cristaleria'), ('manteleria', 'Manteleria'), ('mesas', 'Mesas'), ('sillas', 'Sillas'), ('otros', 'Otros')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.CharField(choices=[('bar', 'Bar'), ('aperitivos', 'Aperitivos'), ('entrada', 'Entrada'), ('plato_principal', 'Plato Principal'), ('postre', 'Postre'), ('personal', 'Personal'), ('vajilla_cristaleria', 'Vajilla y Cristalería'), ('decoracion', 'Decoración'), ('torta', 'Torta')], default='bar', max_length=30),
        ),
    ]
