# Generated by Django 4.2 on 2023-07-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0026_servicio_descservicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='descServicio',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Descripción del Servicio'),
        ),
    ]
