# Generated by Django 4.2 on 2023-07-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0027_alter_servicio_descservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
