# Generated by Django 4.2 on 2023-07-03 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0028_cotizacion_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('nroCotizacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WebSE.cotizacion', verbose_name='Numero de la Cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSE.servicio')),
            ],
        ),
    ]
