# Generated by Django 4.2 on 2023-07-03 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0029_detallecotizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecotizacion',
            old_name='nroCotizacion',
            new_name='cotizacion',
        ),
    ]
