# Generated by Django 4.2 on 2023-07-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0030_rename_nrocotizacion_detallecotizacion_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='nombre_cotizacion',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre de la Cotizacion'),
        ),
    ]
