# Generated by Django 4.2 on 2023-07-03 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0031_detallecotizacion_nombre_cotizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='nombre_cotizacion',
        ),
    ]
