# Generated by Django 4.2 on 2023-07-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0032_remove_detallecotizacion_nombre_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebSE.cotizacion', verbose_name='Numero de la Cotizacion'),
        ),
    ]
