# Generated by Django 4.2 on 2023-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0035_remove_cotizacion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecotizacion',
            name='cantidad',
            field=models.IntegerField(default=''),
        ),
    ]
