# Generated by Django 4.2 on 2023-07-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSE', '0036_alter_detallecotizacion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='subtipo_servicio',
            field=models.CharField(blank=True, choices=[('destilado', 'Destilado'), ('bebida', 'Bebida'), ('bar_adicional', 'Bar Adicional'), ('canapes', 'Canapés'), ('tapaditos', 'Tapaditos'), ('brochetas', 'Brochetas'), ('empanadas_cocktail', 'Empanadas Cocktail'), ('menu_normal', 'Menu Normal'), ('menu_ninos', 'Menu Niños'), ('bartender', 'Bartender'), ('garzón/a', 'Garzón/a'), ('cocinero', 'Cocinero'), ('fotógrafo/a', 'Fotógrafo/a'), ('dj', 'DJ'), ('vajilla', 'Vajilla'), ('cristaleria', 'Cristaleria'), ('manteleria', 'Manteleria'), ('mesas', 'Mesas'), ('sillas', 'Sillas'), ('otros', 'Otros')], default='', max_length=100),
        ),
    ]
